BUG: Fix issue with non-pixi environment running commands
While a pixi home directory was created in the build dashboard, no configuration files existed causing the following:

Error:   × could not find pixi.toml or pyproject.toml with tool.pixi at directory